openapi: 3.0.3

info:
  title: Self Service API
  description: Self Service application REST API
  version: 1.0.0

servers:
  - url: /api/v1

security:
  - bearerAuth: []

paths:

  /users/me:
    get:
      summary: Get current authenticated user
      operationId: getCurrentUser
      tags:
        - User
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                $ref: './components/schemas.yaml#/UserResponse'

        '401':
          $ref: './components/responses.yaml#/Unauthorized'

        '500':
          $ref: './components/responses.yaml#/InternalServerError'

    put:
      summary: Update current authenticated user
      operationId: updateCurrentUser
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas.yaml#/UpdateUserRequest'

      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: './components/schemas.yaml#/UserResponse'

        '400':
          $ref: './components/responses.yaml#/BadRequest'

        '401':
          $ref: './components/responses.yaml#/Unauthorized'

        '500':
          $ref: './components/responses.yaml#/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      $ref: './components/security.yaml#/bearerAuth'