package com.sails.ai.selfserviceapi.onboarding.generate;

import com.sails.ai.selfserviceapi.deploypipeline.manifest.ContainerRole;
import com.sails.ai.selfserviceapi.deploypipeline.manifest.ManifestContainer;
import com.sails.ai.selfserviceapi.deploypipeline.manifest.ManifestRequirement;
import com.sails.ai.selfserviceapi.deploypipeline.manifest.PocManifest;
import com.sails.ai.selfserviceapi.deploypipeline.manifest.Resources;
import com.sails.ai.selfserviceapi.deploypipeline.manifest.Scaling;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;
import org.springframework.stereotype.Component;

/**
 * Renders a {@link PocManifest} as a commented {@code poc.yaml}, hand-built rather than dumped
 * through a generic YAML serializer — matching {@code ManifestParser}'s own preference for explicit
 * field-by-field code, and the only way to reproduce {@code docs/poc.yaml.template}'s inline
 * comments at all (a {@code Yaml.dump()} call has no notion of them).
 *
 * <p>Every value that reaches this class already passed {@code ManifestValidator} — this writer's
 * only job is to render it faithfully, never to invent or correct a value.
 */
@Component
public class ManifestYamlWriter {

    private static final Pattern SIMPLE_SCALAR = Pattern.compile("^[A-Za-z0-9._/${}-]+$");
    private static final Pattern LOOKS_LIKE_NUMBER = Pattern.compile("^-?\\d+(\\.\\d+)?$");

    public String write(PocManifest manifest, List<String> assumptions) {
        StringBuilder out = new StringBuilder();
        writeHeader(out);
        writeAssumptions(out, assumptions);
        writeContainers(out, manifest.containers());
        writeResources(out, manifest.resources());
        writeScaling(out, manifest.scaling());
        writeNotes(out);
        return out.toString();
    }

    private void writeHeader(StringBuilder out) {
        out.append("""
                # yaml-language-server: $schema=./poc.schema.json
                #
                # poc.yaml — generated by the platform's onboarding checker. Review it, then commit it at
                # your repository root as poc.yaml or poc.yml.
                #
                # Every value here already passed the platform's own validator, but the platform read your
                # repository, not your intent — check container roles, ports and env values against what your
                # code actually does before committing.

                """);
    }

    private void writeAssumptions(StringBuilder out, List<String> assumptions) {
        if (assumptions == null || assumptions.isEmpty()) {
            return;
        }
        out.append("# --- Assumptions the generator made — check these first. --------------------\n");
        for (String assumption : assumptions) {
            for (String line : wrap(assumption)) {
                out.append("# ").append(line).append('\n');
            }
        }
        out.append('\n');
    }

    private void writeContainers(StringBuilder out, List<ManifestContainer> containers) {
        out.append("containers:\n");
        for (ManifestContainer container : containers) {
            writeContainer(out, container);
        }
        out.append('\n');
    }

    private void writeContainer(StringBuilder out, ManifestContainer container) {
        out.append("  - name: ").append(container.name()).append('\n');
        String roleComment = container.role() == ContainerRole.INGRESS
                ? "# receives all external traffic"
                : "# reachable from other containers, never from a browser";
        out.append("    role: ").append(container.role().name().toLowerCase()).append(' ').append(roleComment).append('\n');
        out.append("    dockerfile: ").append(container.dockerfile()).append(" # path from the repository root\n");
        out.append("    context: ").append(container.context()).append(" # also from the repository root\n");
        if (container.port() != null) {
            out.append("    port: ").append(container.port()).append('\n');
        }
        if (container.health() != null && !container.health().isBlank()) {
            out.append("    health: ").append(container.health()).append('\n');
        }
        writeEnv(out, container.env());
        writeRequires(out, container.requires());
    }

    private void writeEnv(StringBuilder out, Map<String, String> env) {
        if (env == null || env.isEmpty()) {
            return;
        }
        out.append("    env:\n");
        env.forEach((key, value) -> out.append("      ").append(key).append(": ").append(scalar(value)).append('\n'));
    }

    private void writeRequires(StringBuilder out, List<ManifestRequirement> requires) {
        if (requires == null || requires.isEmpty()) {
            return;
        }
        out.append("    requires:\n");
        for (ManifestRequirement requirement : requires) {
            out.append("      - name: ").append(requirement.name()).append('\n');
            out.append("        secret: ").append(requirement.secret()).append('\n');
        }
    }

    private void writeResources(StringBuilder out, Resources resources) {
        if (resources == null || (resources.cpu() == null && resources.memory() == null)) {
            return;
        }
        out.append("# --- Applies to the ingress container. Sidecars get Cloud Run's defaults. -----\n");
        out.append("resources:\n");
        if (resources.cpu() != null) {
            out.append("  cpu: \"").append(resources.cpu()).append("\"\n");
        }
        if (resources.memory() != null) {
            out.append("  memory: ").append(resources.memory()).append('\n');
        }
        out.append('\n');
    }

    private void writeScaling(StringBuilder out, Scaling scaling) {
        if (scaling == null || (scaling.min() == null && scaling.max() == null)) {
            return;
        }
        out.append("# --- Optional. Omit for Cloud Run's own defaults (0 and 100). -----------------\n");
        out.append("scaling:\n");
        if (scaling.min() != null) {
            out.append("  min: ").append(scaling.min()).append('\n');
        }
        if (scaling.max() != null) {
            out.append("  max: ").append(scaling.max()).append('\n');
        }
        out.append('\n');
    }

    private void writeNotes(StringBuilder out) {
        out.append("""
                # =============================================================================
                # Notes worth reading once
                # =============================================================================
                #
                # ${...} placeholders — everything you can reference
                #
                #   ${self.port}               this container's port
                #   ${self.name}               this container's name
                #   ${services.<name>.url}     http://localhost:<that container's port>
                #   ${services.<name>.host}    localhost
                #   ${services.<name>.port}    that container's port, bare
                #   ${poc.slug}                your POC's slug
                #   ${platform.apiUrl}         the platform API, for verifying launch tokens
                #   ${portal.origin}           the one origin allowed to frame your POC
                #
                #   A reference that names one of those roots but doesn't resolve is an error, and you'll
                #   see it before anything is built. Anything else is left alone as ordinary text.
                #
                # requires: — secrets, and why they are not in env:
                #
                #   Anything under env: is committed to git in clear text, so a password or an API key
                #   cannot live there. Declare the NAME instead and leave the value out of the repository —
                #   Cloud Run resolves it from Secret Manager when the container starts. 'secret: true' is
                #   required today; a requirement without it is rejected rather than quietly unsatisfied.
                #
                # what you cannot set
                #
                #   PORT, POC_SLUG, PLATFORM_API_URL and PORTAL_ORIGIN, and anything starting with SAILS_
                #   or SVC_. The platform owns those. Read them with a placeholder under your own name.
                #
                # the filename
                #
                #   poc.yaml or poc.yml, at the repository root. Both work.
                """);
    }

    private String scalar(String value) {
        if (value == null) {
            return "\"\"";
        }
        if (!value.isEmpty() && SIMPLE_SCALAR.matcher(value).matches() && !LOOKS_LIKE_NUMBER.matcher(value).matches()) {
            return value;
        }
        return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }

    private List<String> wrap(String text) {
        List<String> lines = new ArrayList<>();
        StringBuilder line = new StringBuilder();
        for (String word : text.split("\\s+")) {
            if (line.length() + word.length() + 1 > 88) {
                lines.add(line.toString());
                line.setLength(0);
            }
            if (!line.isEmpty()) {
                line.append(' ');
            }
            line.append(word);
        }
        if (!line.isEmpty()) {
            lines.add(line.toString());
        }
        return lines;
    }
}
