package com.sails.ai.selfserviceapi.onboarding.generate.dockerfile;

import static org.assertj.core.api.Assertions.assertThat;

import com.sails.ai.selfserviceapi.onboarding.generate.stack.StackKind;
import java.util.EnumMap;
import java.util.Map;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Every {@link StackKind} except {@code UNKNOWN} must render a working Dockerfile: no unfilled
 * {@code {{placeholder}}} left over, and zero ERROR/WARNING findings from the real
 * {@link DockerfileLinter} at the stack's default 8080 port — the same bar a model-drafted
 * Dockerfile has to clear, proven here for every vetted template instead.
 */
class DockerfileTemplatesTest {

    private final DockerfileTemplates templates = new DockerfileTemplates();
    private final DockerfileLinter linter = new DockerfileLinter();

    /** Representative params for each stack — enough to fill every placeholder its template uses. */
    private static Map<StackKind, Map<String, String>> fixtureParams() {
        Map<StackKind, Map<String, String>> params = new EnumMap<>(StackKind.class);
        params.put(StackKind.ANGULAR_SPA, Map.of("nodeVersion", "20", "installCmd", "npm ci", "distDir", "dist/web/browser"));
        params.put(StackKind.VITE_SPA, Map.of("nodeVersion", "22", "installCmd", "npm ci", "distDir", "dist"));
        params.put(StackKind.CRA_SPA, Map.of("nodeVersion", "22", "installCmd", "npm ci", "distDir", "build"));
        params.put(StackKind.NEXTJS, Map.of("nodeVersion", "22", "installCmd", "npm ci"));
        params.put(StackKind.NODE_SERVER, Map.of("nodeVersion", "22", "installCmd", "npm ci", "startCmd", "node server.js"));
        params.put(StackKind.STATIC_SITE, Map.of());
        params.put(StackKind.JAVA_MAVEN, Map.of("javaVersion", "21", "buildCmd", "./mvnw -B -DskipTests package",
                "runArgs", " --server.port=${PORT:-8080} --server.address=0.0.0.0"));
        params.put(StackKind.JAVA_GRADLE, Map.of("javaVersion", "21", "buildCmd", "./gradlew build -x test", "runArgs", ""));
        params.put(StackKind.PYTHON_FASTAPI, Map.of("pythonVersion", "3.12", "installCmd", "-r requirements.txt", "appModule", "main:app"));
        params.put(StackKind.PYTHON_FLASK, Map.of("pythonVersion", "3.12", "installCmd", "-r requirements.txt", "appModule", "app:app"));
        params.put(StackKind.PYTHON_DJANGO, Map.of("pythonVersion", "3.12", "installCmd", "-r requirements.txt", "appModule", "app.wsgi:application"));
        params.put(StackKind.PYTHON_STREAMLIT, Map.of("pythonVersion", "3.12", "installCmd", "-r requirements.txt", "entryScript", "main.py"));
        params.put(StackKind.PYTHON_GRADIO, Map.of("pythonVersion", "3.12", "installCmd", "-r requirements.txt", "entryScript", "app.py"));
        params.put(StackKind.GO, Map.of("goVersion", "1.23", "mainPackage", "./cmd/server"));
        params.put(StackKind.DOTNET, Map.of("dotnetVersion", "8.0", "assemblyName", "Api"));
        return params;
    }

    private static Stream<StackKind> everyTemplatedStack() {
        return fixtureParams().keySet().stream();
    }

    @ParameterizedTest
    @MethodSource("everyTemplatedStack")
    void rendersWithNoPlaceholderLeftUnfilled(StackKind kind) {
        String dockerfile = templates.renderDockerfile(kind, fixtureParams().get(kind));

        assertThat(dockerfile).doesNotContain("{{");
        assertThat(dockerfile).contains("Generated by the POC generator");
        assertThat(dockerfile).contains("EXPOSE 8080");
    }

    @ParameterizedTest
    @MethodSource("everyTemplatedStack")
    void rendersADockerignoreWithNoPlaceholderLeftUnfilled(StackKind kind) {
        String dockerignore = templates.renderDockerignore(kind, fixtureParams().get(kind));

        assertThat(dockerignore).doesNotContain("{{");
    }

    /** The bar every generated Dockerfile has to clear — proven here for the vetted templates themselves. */
    @ParameterizedTest
    @MethodSource("everyTemplatedStack")
    void rendersACleanDockerfileByTheRealLinter(StackKind kind) {
        String dockerfile = templates.renderDockerfile(kind, fixtureParams().get(kind));

        assertThat(linter.lint(dockerfile, 8080))
                .describedAs("lint findings for " + kind)
                .noneSatisfy(f -> assertThat(f.severity()).isIn(LintFinding.Severity.ERROR, LintFinding.Severity.WARNING));
    }

    @Test
    void rendersTheSharedNginxConfigWithLiteralShellPortSyntaxUntouched() {
        String config = templates.renderNginxConfig(false);

        assertThat(config).contains("listen       ${PORT};");
        assertThat(config).doesNotContain("{{");
        assertThat(config).doesNotContain("proxy_pass");
    }

    @Test
    void rendersTheWithBackendNginxConfigProxyingApiToBackendUrl() {
        String config = templates.renderNginxConfig(true);

        assertThat(config).contains("listen       ${PORT};");
        assertThat(config).contains("proxy_pass ${BACKEND_URL}/;");
        assertThat(config).doesNotContain("{{");
    }

    @Test
    void failsLoudlyOnAnUnfilledPlaceholderRatherThanEmittingItLiterally() {
        org.assertj.core.api.Assertions.assertThatThrownBy(
                        () -> templates.renderDockerfile(StackKind.GO, Map.of()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("goVersion");
    }

    @Test
    void everyEnumeratedStackExceptUnknownHasATemplate() {
        for (StackKind kind : StackKind.values()) {
            if (kind == StackKind.UNKNOWN) {
                continue;
            }
            assertThat(templates.hasTemplate(kind)).describedAs(kind.name()).isTrue();
        }
    }
}
