package com.sails.ai.selfserviceapi.file.storage;

/**
 * The object layout, in one place because three different operations have to agree on it: upload
 * writes it, download reads it, and purge deletes by prefix.
 *
 * <p>User-first ({@code users/<userId>/pocs/<pocId>/<fileId>}) because purge is the dominant bulk
 * operation and is scoped to a user, so it stays a single prefix delete no matter how many POCs
 * that user touched. Per-POC listing is still a clean prefix underneath, so nothing is given up.
 *
 * <p>The path carries {@code pocId} rather than {@code slug}: a slug is descriptive text that can
 * be corrected or renamed, and a rename must not orphan a user's documents.
 */
public final class ObjectPaths {

    private ObjectPaths() {
    }

    /** Everything belonging to one user, across every POC. The unit purge deletes. */
    public static String userPrefix(String userId) {
        return "users/%s/".formatted(userId);
    }

    /** Everything belonging to one (user, POC) pair. */
    public static String pairPrefix(String userId, long pocId) {
        return "users/%s/pocs/%d/".formatted(userId, pocId);
    }

    /**
     * One object. {@code fileId} is generated by the caller — the uploaded filename never appears
     * here, which removes path traversal, filename collisions, and the disclosure of a name like
     * "Q3-layoffs-J-Smith.pdf" into bucket listings and access logs that outlive the object.
     */
    public static String object(String userId, long pocId, String fileId) {
        return pairPrefix(userId, pocId) + fileId;
    }
}
